### ISSUE TITLE
Init of DB from 'docker-entrypoint-initdb.d' not working

### ISSUE THREAD

**Issue by NathHorrigan** [docker-library/mariadb#119]
This is similar to #62 - I have a folder called db-init which has a file called `backup.sql` with permissions of 777 and below is snippet of my docker-compose.yml

```
mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tuc.staging
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
```
