### ISSUE TITLE
mariadb:10.2 error after image upgrade from 10.1

### ISSUE THREAD

**Issue by Brightside56** [docker-library/mariadb#124]
Hello. I have strange issue with upgrading mariadb 10.1 -> 10.2 on production in docker container. it was ok when project was running 10.1 image, but after I changed version to 10.2 mysql starts, however I receive following error:

`ERROR 1524 (HY000): Plugin 'auth_socket' is not loaded`

I'm running project via docker-compose (config is default)

```
  db:
    image: mariadb:10.2
    volumes:
      - ./../db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwordtest
      - MYSQL_DATABASE=test
```

Also there is no documentation about how to upgrade mariadb container image
