### ISSUE TITLE
Add the possibility to accept host or disable binding 

### ISSUE THREAD

**Issue by Vad1mo** [docker-library/mariadb#14]
I am using mariadb 10.0.19 with dnsdock to avoid hard links between fpm and mariadb. 

This is my docker-compose file
```
dnsdock:
  image: tonistiigi/dnsdock
  hostname: dnsdock
  command: -ttl=30
  restart: always
  dns:
    - 172.17.42.1
    - 8.8.8.8
  ports:
    - "8080:80"
    - "172.17.42.1:53:53/udp"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

wordpress:
  image: wordpress:fpm
  environment:
    WORDPRESS_DB_HOST: mariadb.docker
    WORDPRESS_DB_USER: wp
    WORDPRESS_DB_PASSWORD: "1234"
  volumes:
    - /data/wp:/var/www/html

mariadb:
  image: mariadb:10.0.19
  volumes:
    - /data/mariadb:/var/lib/mysql
  environment:
    MYSQL_USER: wp
    MYSQL_PASSWORD: "1234"
    MYSQL_ROOT_PASSWORD: "1234root"
```

```
...
mariadb_1   | 150526 11:08:01 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1   | 150526 11:08:01 [Note] Server socket created on IP: '::'.
mariadb_1   | 150526 11:08:01 [Note] Event Scheduler: Loaded 0 events
mariadb_1   | 150526 11:08:01 [Note] Reading of all Master_info entries succeded
mariadb_1   | 150526 11:08:01 [Note] Added new Master_info '' to hash table
mariadb_1   | 150526 11:08:01 [Note] mysqld: ready for connections.
mariadb_1   | Version: '10.0.19-MariaDB-1~wheezy-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb_1   | 150526 11:08:01 [Warning] IP address '172.17.1.50' could not be resolved: Name or service not known
wordpress_1 | 
wordpress_1 | Warning: mysqli::mysqli(): (HY000/1130): Host '172.17.1.50' is not allowed to connect to this MariaDB server in - on line 10
wordpress_1 | 
wordpress_1 | MySQL Connection Error: (1130) Host '172.17.1.50' is not allowed to connect to this MariaDB server
```

The problem is that wordpress '172.17.1.50` is not allowed in mariadb. So I need to have a way to add a host to mariadb or disable the binding. Of course I can change that myself in the dockerfile but then I would have to fork the official image and work on my own with that, which I would like to avoid.
