### ISSUE TITLE
Connection refused from inside the container

### ISSUE THREAD

**Issue by ohcibi** [docker-library/mariadb#140]
I tried to use this container with docker-compose as described in the example:

```yaml
version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

But when i start it with `docker run up` and then try to login as root I get a connection refused error. Also when I go into the `adminer` container and install mysql-client and try to connect, I also get the connection refused error. When I export a port from  the mariadb container and connect from the host to it as with a normal mariadb-server, it can connect properly.

Am I missing something or is there a bug?

```
$ docker --version
Docker version 17.09.0-ce, build afdb6d4
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
```
