### ISSUE TITLE
Support multiple databases creation

### ISSUE THREAD

**Issue by visay** [docker-library/mariadb#15]
Currently I only have the option to create only one database in my docker-compose.yml

```
db:
  image: mariadb:10.0
  environment:
    MYSQL_DATABASE: mydbname
```

It would be good if multiple databases is supported (something similar to this merge request in mysql https://github.com/docker-library/mysql/pull/18/files), so I can write:

```
db:
  image: mariadb:10.0
  environment:
    MYSQL_DATABASES:
      - mydbname1
      - mydbname2
```

**Comment by yosifkit** [comment]
Although your yaml syntax would not work, there was discussion of letting MYSQL_DATABASE be a space separated string of databases: https://github.com/docker-library/mysql/pull/18.

**Comment by bennythomps** [comment]
Keep in mind, best practice would be to have a separate container for each application if that's what you're trying to do. Maybe your one application for some reason needs more than one database, though.

**Comment by Crafter6432** [comment]
+1

**Comment by Vingtoft** [comment]
+1

**Comment by madalinignisca** [comment]
-1

the idea for docker is minimalism. one database per container. you can start multiple containers with different databases.

**Comment by alexander-robbin** [comment]
Probably ok during development. What about the additional resource required to run another container? And additional configurations needed, especially when I need a mysql cluster?

**Comment by madalinignisca** [comment]
You can make a simple Dockerfile using this one as the image source and just add your own extra env variables to add more databases to your service. Easy as that. The base one isn't supposed to cover all possible scenarios we think about, but to offer the foundation on which we build the solutions to our problems.

Building it it might take an extra second or less ;)

**Comment by amir20** [comment]
Reading the README file suggests

> Furthermore, it will execute files with extensions .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d.

So adding your own .sql file should be able to create multiple databases.

**Comment by alexanikanov** [comment]
+1

**Comment by armansd** [comment]
Just update startup file under mysql directory:

DROP USER IF EXISTS 'MYSQL_USER';
CREATE USER 'MYSQL_USER'@'%';
CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;
GRANT ALL ON MYSQL_DATABASE.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
--------------your new testDB----------------------
CREATE DATABASE IF NOT EXISTS testDB;
GRANT ALL ON testDB.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';

**Comment by sirgalleto** [comment]
What's the status of this issue? why is clossed?

**Comment by visay** [comment]
@sirgalleto because you can already do it with our own script if they are mounted into `/docker-entrypoint-initdb.d`.

See the description at https://hub.docker.com/_/mariadb/ section "Initializing a fresh instance"

**Comment by Denis4yk** [comment]
To my point of view it could be quite useful and should be reopened

**Comment by abagayev** [comment]
Created clear example of docker-compose with multiple databases, just use for your purposes:
https://github.com/abagayev/docker-bootstrap-collection/tree/master/mysql-few-databases

**Comment by MKagesawa** [comment]
Take a look here: https://gist.github.com/MKagesawa/a03892b8c44c015cd991c2c5311f1768
You can pass a shell script creating the dbs
```
# The official MySQL (https://hub.docker.com/_/mysql/) supports only one MYSQL_DATABASE environment variable.
# By modifying the entrypoint and passing shell script, you can create multiple dbs without having to make a mysql image just for this purpose.
  
version: '3'

services:
  # Some other service connecting to mysql
  
  db:
    image: mysql:5.6
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS firstDB; CREATE DATABASE IF NOT EXISTS secondDB;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 3306:3306 
```
