### ISSUE TITLE
Docker for Windows: cannot write on shared volumes

### ISSUE THREAD

**Issue by rahonalab** [docker-library/mariadb#152]
as already mentioned here #95 , mariadb container on windows cannot write its database files on a shared volume. Here is a snippet of my docker-compose.yaml

```yaml
sql:
    image: mariadb
    env_file: ./secrets.env
    domainname: ${DOMAINNAME}
    hostname: ${FIRSTNAME}-sql
    volumes:
      - ./${FIRSTNAME}-container/lib/mysql:/var/lib/mysql
  web:
   image: rahonabe/icinga2-web
   env_file: ./secrets.env
   links:
     - sql
     - core
   domainname: ${DOMAINNAME}
   hostname: ${FIRSTNAME}-web
   build: 
    context: ./web
   ports:
     - 80:80
   volumes:
     - ./${FIRSTNAME}-container/etc/icingaweb2:/etc/icingaweb2
     - ./${FIRSTNAME}-container/webroot_icingaweb2:/usr/share/icingaweb2
     - ./${FIRSTNAME}-container/webroot_nagvis:/usr/local/nagvis
     - ./${FIRSTNAME}-container/lib/php5/sessions:/var/lib/php5/sessions
     - ./${FIRSTNAME}-container/log/apache2:/var/log/apache2
     - ./${FIRSTNAME}-container/certs:/etc/apache2/ssl:ro
     - ./${FIRSTNAME}-container/perfdata:/var/lib/pnp4nagios/perfdata
     - ./${FIRSTNAME}-container/etc/pnp4nagios:/etc/pnp4nagios
   volumes_from:
     - core
     - sql
```
