### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

### ISSUE THREAD

**Issue by MuhammadZaidSE** [docker-library/mariadb#157]
When I try to run `mysql` command through bash, I get this error.
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
```
This is my docker-compose file
```
db:
    image: mariadb:10.0.34
    volumes:
      - ./latest_dump.sql:/docker-entrypoint-initdb.d/latest_dump.sql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: *******
```
How can I solve this issue?
