### ISSUE TITLE
Default charset and collation for database

### ISSUE THREAD

**Issue by visay** [docker-library/mariadb#16]
Currently if I define a database to be created on startup, like:

    db:
      image: mariadb:10.0
      environment:
        MYSQL_DATABASE: mydbname

The database gets created through `CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;` command.

Would it make senses to have `DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci` to the create command since that seems to be the recommended standard in most setup (at least for the Framework I'm using :D)?

If that is not preferred, at least an option that I can define it myself should be available as variable in docker-compose.yml

**Comment by thaJeztah** [comment]
I think this is similar to the feature-request for MySQL; https://github.com/docker-library/mysql/pull/14

**Comment by visay** [comment]
Yes, that's one part for the charset but collation setting is still missing.

**Comment by thaJeztah** [comment]
True! Just referring to that issue, so that (if possible), a single solution can be found for both MySQL and MariaDB :+1:

**Comment by yosifkit** [comment]
+1: https://github.com/docker-library/mysql/pull/14#issuecomment-117348915

**Comment by tianon** [comment]
This is possible today trivially with command-line flags, as noted/demonstrated in the image description: (https://github.com/docker-library/docs/blob/e72d96051254c263821f8fab32f05e0153221ed9/mariadb/README.md#configuration-without-a-cnf-file)

> ```console
$ docker run ... mariadb --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

**Comment by visay** [comment]
@tianon how to integrate these command flags into the docker-compose.yml?

**Comment by tanji** [comment]
@visay You can use the command option to pass a command name and flag.
`command: mysqld --flag --flag --flag`

**Comment by visay** [comment]
@tanji ah yes, working as expected. thanks a lot :)

**Comment by Alexhha** [comment]
Did I miss something but doesn't work for me
```
MariaDB [(none)]> show variables like 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.001 sec)
```

mariadb:10.5
```
# docker inspect mariadb | jq .[].Config.Cmd
[
  "mysqld",
  "--character-set-server=utf8mb4",
  "--collation-server=utf8mb4_unicode_ci"
]
```
docker-compose.yml
```
version: '3'
services:
  mariadb:
    network_mode: host
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - /opt/docker/mariadb/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MARIADB_DATABASE=testdb
      - MARIADB_USER=user
      - MARIADB_PASSWORD=1234567
      - MARIADB_RANDOM_ROOT_PASSWORD=true
```
