### ISSUE TITLE
"ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'" when initializing database via "docker-compose up" for the first time

### ISSUE THREAD

**Issue by AmagicalFishy** [docker-library/mariadb#173]
This is very similar to [this](https://github.com/docker-library/mysql/issues/129) problem, but not the same. That problem is specific to when `MYSQL_USER` is set to `root`. This occurs when `MYSQL_USER` is set via an environment variable. Here is my **docker-compose.yml**:

```
version: '3'

services:
    mariadb:
        container_name: ${SQL_CONTAINER}
        image: mariadb:10.3.7
        ports: 
            - ${SQL_PORTS} 
        volumes:
            - my-datavolume:/soundstat/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
volumes:
    my-datavolume:
```
I use a lot of environment variables, all of which function as expected (except for `MYSQL_USER` and, I'd guess, `MYSQL_PASSWORD`). On the other hand, if I write in the values explicitly, everything works fine. My environment variables are kept in the file `.env`.

If I run `docker-compose up` a second time, the container starts up successfully—but when I check the SQL users, only `root` exists. I also checked the environment variables within the container, and it seems that the problem is that the environment variables `MYSQL_USER` gets set to `root` when I use my own environment variable to set it (regardless of what said variable is); the other ones work just fine, though.

I also made sure $DB_USER wasn't set locally to `root`. :p
