### ISSUE TITLE
Can't connect Wordpress or Drupal to MariaDB

### ISSUE THREAD

**Issue by rifton007** [docker-library/mariadb#189]
Hi everyone and thank you for your help.

I tried to install WordPress or Drupal but I couldn't to install them.
They couldn't to connect to the database.

I use docker-compose from Windows 10 and I can connect to database and create table without problem.
But when I launch blogs's installer, they can't to find the database.

```yaml
web:
    image: "web:php7.1a"
    container_name: web
    volumes:
        - .:/var/www/html
    ports:
        - "80:80"
    links:
        - data
data:
  image: mariadb:10.1
  container_name: data
  environment:
    - MYSQL_ROOT_PASSWORD=0576
  restart: unless-stopped
  volumes:
    - ./docker:/etc/mysql/conf.d
    - ./data:/var/lib/mysql
  ports:
    - "3306:3306"
```

And the log of MariaDB container return me
`[Warning] IP address '172.17.0.1' could not be resolved: Name or service not known`

Could you hehp me to resolve this problem and thank you for your assitance.
