### ISSUE TITLE
datadir volume causes container to stop from starting

### ISSUE THREAD

**Issue by purinda** [docker-library/mariadb#200]
### Issue:
MariaDB docker image consistently fails to start for all versions after "v10.0.28" when trying to mount a host volume as the datadir.

I did test almost all the docker images currently available in https://hub.docker.com/r/library/mariadb/tags/ the only ones I can start successfully are v10.0.27 and .28

### Platform:
- Mac (OSX 10.13.6), using APFS **case insensitive** filesystem
- Docker-machine: boot2docker running on Parallels Desktop Version 14.0.0 Pro (45124) 

part of the `docker-compose.yml` which has the mariadb service mapping.

### docker-compose.yml
```
version: "2.4"
services:
    db:
        image: mariadb:10.0.28
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./store/maria-db:/var/lib/mysql
        command: 'mysqld --innodb-flush-method=fsync'
        ports:
            - 3306:3306
```

### Logs:
Samples of failing versions
[10.0.30.log](https://github.com/docker-library/mariadb/files/2377375/10.0.30.log)
[10.2.17.log](https://github.com/docker-library/mariadb/files/2377376/10.2.17.log)
[10.3.9.log](https://github.com/docker-library/mariadb/files/2377377/10.3.9.log)

Working version:
[10.0.28.working.log](https://github.com/docker-library/mariadb/files/2377374/10.0.28.working.log)
