### ISSUE TITLE
Error starting mariadb on every host reboot

### ISSUE THREAD

**Issue by sprnza** [docker-library/mariadb#201]
Hi there!
I've got a wierd issue I don't know how to debug. Every single reboot I get mariadb unable to start with this error:

```
2018-09-19  4:29:31 0 [Note] Plugin 'FEEDBACK' is disabled.
2018-09-19  4:29:31 0 [Note] Recovering after a crash using tc.log                                                               
2018-09-19  4:29:31 0 [ERROR] Bad magic header in tc log
2018-09-19  4:29:31 0 [ERROR] Crash recovery failed. Either correct the problem (if it's, for example, out of memory error) and restart, or delete tc log and start mysqld with --tc-heuristic-recover={commit|rollback}                                           
2018-09-19  4:29:31 0 [ERROR] Can't init tc log
2018-09-19  4:29:31 0 [ERROR] Aborting

```

my docker-compose looks like this

```
    mariadb:                                                                                                                      
        image: mariadb                                                                                                            
        restart: always                                                                                                           
        ports:                                                                                                                    
            - "3306:3306"                                                                                                         
        volumes:                                                                                                                  
            - /var/lib/mysql:/var/lib/mysql                                                                                       
        environment:                                                                                                              
            MYSQL_ROOT_PASSWORD: my+pass+here                                                                                          
        networks:                                                                                                                 
            - default                                                                                                             
        container_name: mariadb                                                                                                   
        labels:                                                                                                                   
            - "com.centurylinklabs.watchtower.enable=true"                                                                        
            - "traefik.enable=false"   
```
After I remove tc.log the container starts immediately.
What could be wrong? Not set uid? Very annoying
