### ISSUE TITLE
docker-compose on Window does not use environment

### ISSUE THREAD

**Issue by dmenne** [docker-library/mariadb#218]
The simple `docker-compose` below works as expected in Ubuntu. When I test it in container-bash, I can connect with `mysql` and the password , and the database `formr` was created (`SHOW DATABASES`).

When I run the same in Windows 10, MariaDB starts ok, but I can only access it with `root` and no password; user and database are not created. It behaves  as if enviroment was not honored.

I suspected something like a stale volume, but I have used `-v, docker volume ls` and `docker volume rm` to make sure that there is no volume interfering.

Using MARIADB_ variables, bitnami works fine in Windows.

Versions of Docker were current as of today 2 CPU, 7.5 GB Memory

```
version: '3.7'
services:
  db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    container_name: formr_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: formr
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: formr
```
