### ISSUE TITLE
cannot start mariadb service after stop and start in docker-compose

### ISSUE THREAD

**Issue by dmatis2** [docker-library/mariadb#225]
Hi all, 
today I wanted to orchestrate mariadb with PhpMyAdmin. Here is `docker-compose.yml`

```
version: '3'
services:
        db:
                image: mariadb
                command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                networks:
                        - backend
                volumes:
                        - db_data:/var/lib/mysql
        pma:
                image: phpmyadmin/phpmyadmin
                ports:
                        - "8080:80"
                environment:
                        - MYSQL_USERNAME=root
                        - MYSQL_ROOT_PASSWORD=root
                depends_on:
                        - db
                networks:
                        - backend
networks:
        backend:

volumes:
        db_data:
```

at first I did `docker-compose -p dbs up`, wait some time to get ready and it worked, I was able to create databases, tables, rows etc. After some time I did `docker-compose -p dbs stop` to stop containers, but remove neither them nor volume and network. After a hour (computer was up all the time) I did `docker-compose -p dbs start` to start them, waited some time and log into pma but it didn't log me there ... So I checked the logs (`docker logs <container id>`) and the last line said `[ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist`. Please help me

I'm using Docker Desktop for Windows on Windows 10
