### ISSUE TITLE
Documentation mentions MARIADB_ROOT_PASSWORD etc, but those don't work

### ISSUE THREAD

**Issue by baszoetekouw** [docker-library/mariadb#238]
According to the documentation at https://hub.docker.com/r/mariadb/server the env variables to use are prefixed with `MARIADB_`.  However, those don't seem to be accepted; only the `MYSQL_`-variants seem to work.

To reproduce, docker-compose.yml:
```yml 
---
version: '3.3'
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secr1t
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: secr1t
```
results in:
```
root@sandbox1:/opt/wordpress# /usr/local/bin/docker-compose up
Pulling db (mariadb:10.3)...
10.3: Pulling from library/mariadb
Digest: sha256:85b7eb2b3edf110a08bd3c346481d44a18e46d45cb813fa73112b7276823bf9f
Status: Downloaded newer image for mariadb:10.3
Recreating wordpress_db_1 ... done
Attaching to wordpress_db_1
db_1  | error: database is uninitialized and password option is not specified 
db_1  |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
wordpress_db_1 exited with code 1
```
