### ISSUE TITLE
Cant connect to mariadb

### ISSUE THREAD

**Issue by rikipm** [docker-library/mariadb#264]
Im using docker for windows on windows 1903

My docker-compose.yml
```
db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOSTS: db
    ports:
      - "8080:80"
    depends_on:
      - db
```

After I trying to login in phpmyadmin, I see this

![Untitled](https://user-images.githubusercontent.com/13685393/65823691-afc3df80-e263-11e9-800b-4120d77af2bb.png)

`docker-compose logs db | grep Warning`:
```
 |?[0m 2019-09-28 22:47:36 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 22:47:36 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 22:47:36 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:35 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:38:50 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:32 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.3' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:53 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:46:15 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
```
[Full logs](https://pastebin.com/97xTdcWc)

**Comment by yosifkit** [comment]
Possibly this helps: https://github.com/docker-library/postgres/issues/203#issuecomment-255200501

**Comment by tkaprol** [comment]
I have the same issue, mariadb image does not setup itself with given password from environment and also the database is not created from MYSQL_DATABASE parameter. I can get variables by printenv command inside container.

Also mysql starts with -skip-networking parameter so I can not connect to mysql from anywhere anymore.

The setup were working, I deployed same setup to many different servers.

**Comment by yosifkit** [comment]
@tkaprol, it sounds like you are running into #262 or #261.  The [`--skip-networking`](https://github.com/docker-library/mariadb/blob/bf675caa56e4a1b462c665d1cded137f13c33753/docker-entrypoint.sh#L105) is on purpose in order that the users and database (and `docker-entrypoint-initdb.d` scripts) be fully complete before it exposed remotely.

**Comment by boldt** [comment]
I had the same issue. I see two problems in your configuration

1) The environment-variable for the phpmyadmin-container is not called `MYSQL_ROOT_PASSWORD`
2) phpmyadmin required the `mysql_native_password`-plugin

Here is a working example:

```yaml
version: '3.6'

services:

  db:
    image: mariadb:10.4.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    restart: always
    depends_on:
    - db
    environment:
    - PMA_HOST=db
    - PMA_PORT=3306
    - PMA_USER=test
    - PMA_PASSWORD=test
    ports:
    - "3333:80"
```

Just run it, wait a minute and open http://localhost:3333/
