### ISSUE TITLE
docker compose fail. unknown/unsupported storage engine: InnoDB

### ISSUE THREAD

**Issue by samayo** [docker-library/mariadb#267]
I have a docker-compose file where I run mariadb, nginx, php. But Mariadb keeps restarting every second for some reason:

```cmd
$ docker ps
CONTAINER ID        IMAGE        COMMAND                CREATED        STATUS        PORTS                NAMES

a8dd9dfc0865        my_db        "docker-entrypoint.s…"   19 minutes ago      Restarting (1) 6 seconds ago                    foo-db
```
If I check the logs, I see this error:

```cmd
my-db | 2019-10-25  6:32:19 0 [ERROR] InnoDB: Cannot read first page of './ibdata1' I/O error
my-db | 2019-10-25  6:32:19 0 [ERROR] InnoDB: Plugin initialization aborted with error I/O error
my-db | 2019-10-25  6:32:20 0 [Note] InnoDB: Starting shutdown...
my-db | 2019-10-25  6:32:20 0 [ERROR] Plugin 'InnoDB' init function returned error.
my-db | 2019-10-25  6:32:20 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
my-db | 2019-10-25  6:32:20 0 [Note] Plugin 'FEEDBACK' is disabled.
my-db | 2019-10-25  6:32:20 0 [ERROR] Unknown/unsupported storage engine: InnoDB
my-db | 2019-10-25  6:32:20 0 [ERROR] Aborting
```

and here is my docker-compose file related to mariadb

```yml
version: '3'

services:
    db:
      container_name: ${APP_NAME}-db
      build:
        context: ./docker/mariadb
      volumes:
          - ./docker/mariadb/scripts:/docker-entrypoint-initdb.d
          - ./.data:/var/lib/mysql
          - ./docker/logs/mariadb:/var/log/mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      ports:
          - '${MYSQL_PORT:-3306}:3306'
      command:
          ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
          
      networks:
        - default
      restart: always

```
