### ISSUE TITLE
Mariadb:10.4.8  can not allow remote root access

### ISSUE THREAD

**Issue by BruceZu** [docker-library/mariadb#269]
I use docker compose to deploy it 

version: "3.7"
```

services:
  portal:
    image: registry.my.com/portal/portal:latest
    restart: always
    ports:
      - "8444:8444"
    environment:
      IS_IN_FMG_VM: "true"
    networks:
      app_net:
        ipv4_address: 169.254.255.50
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - fortiportaldb

  db:
    image: registry.my.com/portal/db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "db_data:/var/lib/mysql"
    networks:
      app_net:
        aliases:
          - mysql
        ipv4_address: 169.254.255.51
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "169.254.255.48/28"
volumes:
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/var/docker/portal/db_data"

```

I deploy it in a VMware VM 
the portal service need wait the db ready before with 
```

function wait_mysql_up() {
    local mysql_service=mysql
    local mysql_port=3306
    local check_command="mysqladmin status -h${mysql_service} -P${mysql_port} -proot"
    eval "$check_command"
    while [ $? -ne 0 ]; do
        echo "MariaDB is not up, wait 3s and try again"
        sleep 3s
        eval "$check_command"
    done
}

```

portal failed to connect the mariadb 
I add some update to enable it works as 
/etc/mysql/mariadb.cnf
```
[mysqld]
skip-networking = 0
skip-bind-address
```
and 
```
sql>  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'IDENTIFIED BY 'root' WITH GRANT OPTION;
sql>   FLUSH PRIVILEGES;
```

My question : should not allowing remote access be by default? 
Is there a related version with this feature? 
Or any suggest to carry out above 2 SQL statement in a customized Dockerfile? 
Thank you!
