### ISSUE TITLE
can not connect to the server, all users are blocked!

### ISSUE THREAD

**Issue by mjodeh** [docker-library/mariadb#286]
I use docker compose:
```
version: '3.6'
services:
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./maria_db_data:/var/lib/mysql
      - ./database/user.sql:/docker-entrypoint-initdb.d/user.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: user
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - test
    ports:
      - 3306:3306
    
  
networks:
  test:
    external: true
```

`docker-compose -v`: docker-compose version 1.24.0
`docker -v`: Docker version 19.03.5, build 633a0ea838
OS: ubuntu 18.04

after running the compose file and I can not connect to it from the host.
on the container:
`docker exec -it c4ca08d31979 /bin/bash
`root@c4ca08d31979:/# mysql -u root -p
I get:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@c4ca08d31979:/# mysql -u test -p
ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)
