### ISSUE TITLE
Mariadb docker-compose up error

### ISSUE THREAD

**Issue by juan-montilla** [docker-library/mariadb#316]
Hello guys.. 
Error msg:
`You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD`
docker version:
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683`
docker-compose version
`docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```
docker-compose.yml
```
version: '3.1'
services:

  db:
    image: mariadb:lastest
    build:
      context: .
      args:
        - http_proxy
    volumes:
      - /home/my-home/.tests/mariadb:/var/lib/mysql
      - /home/my-home/.tests/mariadb-logs:/var/log/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD:abc123
      - MYSQL_USER:dev
      - MYSQL_PASSWORD:dev
```

Questions:
1) Please why mariadb does not see that env var? 
2) Why examples does not show dash before env var but docker-compose complains 
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.db.environment contains an invalid type, it should be an object, or an array
`
when i don't use it?

Thanks in advance
