### ISSUE TITLE
Kubernetes cannot run mariadb docker container as an arbitrary user

### ISSUE THREAD

**Issue by zelong430** [docker-library/mariadb#330]
Hi,

I'm trying to deploy a mariadb instance in our enterprise on-perm Kubernetes cluster. The challenge is that our Kubernetes cluster only allow me to deploy pods with a fixed default security context (a fixed specific UID/GID). Therefore, I can't run the pod as root or as any users other than the specific UID/GID allowed. The docker file specific set /var/lib/mysql permission to user mysql:mysql. So when I launch the pod through default docker entry point, mysqld always complains not allowed to created files in /var/lib/mysql due to permission. 

I found this issue https://github.com/docker-library/mariadb/issues/304. Seems like there is a --user option for docker run to only arbitrary non-root user other than mysql to start the db. Are there any similar solution for kubernetes env?

I tried to build my own docker image on top of mariadb like:

`
from mariadb

RUN chmod -R 777 /var/lib/mysql
EXPOSE3306
` 
but this doesn't work. The permission of /var/lib/mysql still restrict to mysql:mysql.

**Comment by wglambert** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  securityContext:
    runAsUser: 1337
    runAsGroup: 1337
    fsGroup: 2000
  volumes:
  - name: mariadb-volume
    emptyDir: {}
  containers:
  - name: mariadb
    image: mariadb
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    volumeMounts:
    - name: mariadb-volume
      mountPath: /var/lib/mysql
    securityContext:
      allowPrivilegeEscalation: false
```

```console
$ kubectl apply -f mariadb.yaml
pod/mariadb created

$ kubectl logs mariadb
. . .
2020-11-04  0:45:21 0 [Note] mysqld: ready for connections.
Version: '10.5.6-MariaDB-1:10.5.6+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution

$ kubectl exec -it mariadb bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
groups: cannot find name for group ID 1337
groups: cannot find name for group ID 2000

I have no name!@mariadb:/$  mysql -u root -proot
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.6-MariaDB-1:10.5.6+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```
