### ISSUE TITLE
Can we use .env file to pass environment variables?

### ISSUE THREAD

**Issue by SnowNooDLe** [docker-library/mariadb#337]
Hey guys, 

Recently joined dev world, a fresh developer here. Please correct me if I am doing something wrong :)

So I am currently working on a web app project with React + Flask and we decided to use MariaDB with SQLAlchemy.
We also decided to use with docker as our React and Flask are also running on docker as well. The current `docker-compose.yml` is like the following code.

**Working fine**
```yaml
# docker-compose.yml

version: "3.8"

services:
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root_test

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
With the code above, it works as we expected, we can put user and user via **adminer** to see what's happening. However,

**Not working**
```yaml
# docker-compose.yml

version: "3.8"

services:
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - 3306:3306
     environment:
       - MYSQL_DATABASE=${DATABASE}
       - MYSQL_USER=${USERNAME}
       - MYSQL_PASSWORD=${PASSWORD}
       - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}

    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
with `.env`
```env
DATABASE=test
USERNAME=user
PASSWORD=user
ROOT_PASSWORD=root_test
```
This is not working as we expected, it gives us the access denied error message.

I also tried parsing `env_file: .env` in the `docker-compose.yml` and still didn't work :(

Is this a related issue to this PR? [Add support for MARIADB_ versions of env vars](https://github.com/docker-library/mariadb/pull/333) or is there a different way of using/parsing `.env` variables to docker-compose.yml?
(I am like 99% confident that the syntax of parsing .env variables is fine as this is how we set up the docker-compose for React and Flask.)

As I could only see the usage of MariaDB docker-compose.yml with specified environment variables instead of using `.env` and I am not sure whether it is a good practice to make those information visible (e.g, password and root_password)

Thanks for reading a long post and happy to get any feedback or answers! :+1:
