### ISSUE TITLE
Host "xxx.xxx.xxx.xxx" is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by ahansson89** [docker-library/mariadb#48]
I get this error on the latest version.

**Comment by tianon** [comment]
Can you provide us a little more information about how you're running it?  I can't seem to reproduce:
```console
$ docker pull mariadb
Using default tag: latest
latest: Pulling from library/mariadb

fdd5d7827f33: Already exists 
a3ed95caeb02: Already exists 
2d9b55a37647: Already exists 
88a4bacbf934: Already exists 
d2f0eb2850d3: Already exists 
e35651814623: Already exists 
12cafcc1e597: Already exists 
b12059a0fd60: Already exists 
9643f0599420: Already exists 
452cf8ba3692: Already exists 
Digest: sha256:de91e4cb58e716a12f0ee204d628ba9c855f217a42f96360181c28beb0e7b075
Status: Image is up to date for mariadb:latest
$ docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb
c5b36b0bf92e473b796e6fc2708c0e747ccaa21ab800d769abc6dbcc4e8f957a
$ docker run -it --link some-mariadb:mysql --rm mariadb sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.12-MariaDB-1~jessie mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SELECT 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

MariaDB [(none)]> 
```

**Comment by peh** [comment]
hey @tianon 
i experience exactly the same behaviour as @ahansson89 is seeing by doing exactly what you did

```
peh@main:~$ docker pull mariadb
Using default tag: latest
latest: Pulling from library/mariadb

fdd5d7827f33: Already exists
a3ed95caeb02: Already exists
2d9b55a37647: Already exists
88a4bacbf934: Already exists
d2f0eb2850d3: Already exists
e35651814623: Already exists
12cafcc1e597: Already exists
b12059a0fd60: Already exists
9643f0599420: Already exists
452cf8ba3692: Already exists
Digest: sha256:de91e4cb58e716a12f0ee204d628ba9c855f217a42f96360181c28beb0e7b075
Status: Image is up to date for mariadb:latest
peh@main:~$ docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb
7895011144d8801751ff93454664ba78e9c328a850e15961401ad05debf5453c
peh@main:~$ docker run -it --link some-mariadb:mysql --rm mariadb sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
ERROR 2003 (HY000): Can't connect to MySQL server on '172.17.0.5' (111 "Connection refused")
peh@main:~$
```

**Comment by Azerothian** [comment]
I use rancher and it likes to setup custom networks for my docker containers which in turn causes the same issue

Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1130] Host '10.42.209.230' is not allowed to connect to this MariaDB server 


```
mariadb:
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: owncloud
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mariadb
  volumes:
  - /opt/docker/owncloud/db:/var/lib/mysql
owncloud:
  environment:
    VIRTUAL_HOST: owncloud..local
    VIRTUAL_PORT: '8080'
  labels:
    io.rancher.container.pull_image: always
  image: owncloud
  links:
  - mariadb:mariadb
  volumes:
  - /opt/docker/owncloud/data:/var/www/html
```
