### ISSUE TITLE
Fail to mount and initialise DB with /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by sebglon** [docker-library/mariadb#62]
if i set sql file on $(pwd)/init-db, and run this command

docker run -v $(pwd)/init-db:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD=tutu
-e MYSQL_DATABASE=tutu -e MYSQL_PASSWORD=tutu mariadb 

Mariadb ignore file /docker-entrypoint-initdb.d
"/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/\* "'

**Comment by yosifkit** [comment]
So, `init-db` is a directory with a file ending in `.sql`?  Is the directory and file readable by user `999` (which is what the sql process runs as)?

**Comment by sebglon** [comment]
Yes init-db is a directory with file endind in .sql ans .sh. this directory is readable by docker an mounter on container with root '770'.

For information this don't work on Mysql but work with postgres images

**Comment by sebglon** [comment]
After than container is started and file is ignored, if i make this command, file is imported:
mysql -u $MYSQL_USER -p$MYSQL_PASSWORD  $MYSQL_DATABASE <  /docker-entrypoint-initdb.d/file.sql 

The .sql file is read and imported on my database.

**Comment by blafasel42** [comment]
any news on this? i have the same issue

**Comment by yosifkit** [comment]
It has to be permissions on the files in the initdb directory.  The only difference for this part between the mariadb and postgres entrypoint scripts is that postgres is still running as the root user when it runs the scripts while mariadb/mysql is running as the `mysql` user in the container.

**Comment by waynetheisinger** [comment]
+1 I've the same issue

**Comment by waynetheisinger** [comment]
if you create your own dockerfile that use extend FROM this mariadb base image and use an ADD to copy the file into the images container it works... but it doesn't work when you load it as a volume

**Comment by waynetheisinger** [comment]
though you have to 777 it because it's owned by root, so @yosifkit might be right when he says its probably permissions...

**Comment by waynetheisinger** [comment]
Actually - this is failing again even when I use the above work around... grr

**Comment by loranger** [comment]
Having the same issue.
I'm not even able to achieve the solution provided by @waynetheisinger.
The only solution I found is to run a bash session within the image and inject my `/docker-entrypoint-initdb.d/dump.sql` manually.
Is there another way ?

**Comment by yosifkit** [comment]
Closing old issue. (still think it is/was permissions)

**Comment by luandro** [comment]
Having the same issue... Should be a better explanation on how to use. Here's my `docker-compose.yml`:

```
version: '2'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
  mysql:
    image: mariadb:latest
    restart: always
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
```

Inside `./wp-data/` there's a `.sql` dump file.
