### ISSUE TITLE
login to docker mariadb with root user

### ISSUE THREAD

**Issue by averlon** [docker-library/mariadb#649]
Hi,
I have installed a mariadb docker image via compose:

```
  db:
    container_name: mariadb
    image: mariadb
    hostname: db
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - /mnt/mariadbdata:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD='<some password without any special characters'
 ```

Now I am trying to run some commands inside the container to create users and grant privileges.

To test the access I tried:
```
docker exec -it mariadb bash -c "mariadb -u root -p<the defined password>"
```

Result:
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

In the documentation I saw that the root user will be created with "%". From my knowledge this should allow to connect from everywhere.

What can I do to connect.

P.S.: I also have installed Adminer in a separate container. Also with this I get a similar error message.
