### ISSUE TITLE
MYSQL_ONETIME_PASSWORD does not have an effect

### ISSUE THREAD

**Issue by jazzfog** [docker-library/mariadb#69]
I am trying to use `MYSQL_ONETIME_PASSWORD` environment variable to force user to change password but it seems like it does not have any effect - I can re-login indefinitely.

Also I do not see mention of this option in [entrypoint file](https://github.com/docker-library/mariadb/blob/21b143d133b2250eb473eb5492cfa38e5d094e62/10.0/docker-entrypoint.sh), unlike, for example, `MYSQL_RANDOM_ROOT_PASSWORD`

```
version: '2'
services:
  mariadb:
    image: mariadb:10
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=passwd
```
