### ISSUE TITLE
Warning: World-writable config file ...

### ISSUE THREAD

**Issue by VeeeneX** [docker-library/mariadb#74]
Hi, I've tried to run mariadb with docker-compose.yml, with simple configuration:

``` yml
version: '2'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/phabricator.cnf:ro
```

Contents of /docker/mysql/mysql.cnf:

``` cnf
[mysqld]
sql_mode=STRICT_ALL_TABLES
ft_stopword_file=/opt/phabricator/resources/sql/stopwords.txt
ft_min_word_len=3
innodb_buffer_pool_size=410M
ft_boolean_syntax=' |-><()~*:""&^'
max_allowed_packet=33554432
```

Docker info

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 155
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.12-boot2docker
Operating System: Boot2Docker 1.11.2 (TCL 7.1); HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: b2d-vagrant
ID: AFJD:COEF:DYKW:NQY4:5LS5:3Y4D:FSL7:TQZK:YDNS:XQNN:HWMA:S7RA
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 41
 Goroutines: 68
 System Time: 2016-08-02T16:42:26.606343039Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Docker version:

```
Client:                                               
 Version:      1.11.2                                 
 API version:  1.23                                   
 Go version:   go1.5.4                                
 Git commit:   b9f10c9                                
 Built:        Wed Jun  1 21:20:08 2016               
 OS/Arch:      linux/amd64                            

Server:                                               
 Version:      1.11.2                                 
 API version:  1.23                                   
 Go version:   go1.5.4                                
 Git commit:   b9f10c9                                
 Built:        Wed Jun  1 21:20:08 2016               
 OS/Arch:      linux/amd64                            
```
